### ISSUE TITLE
关于ktex转png的一点疑问

### ISSUE THREAD

**Issue by yechentide** [Fire-Paw-DST-Manager/DST-Common#1]
你好,我目前在写一个[开源的Go版本的饥荒联机服管理工具](https://github.com/yechentide/dstm),准备加入ktex转png功能,你的代码让我节省了大量时间,太谢谢了!  
但是我转换出来的png总是有瑕疵,如果可能的话,能不能给我一点提示呢.  
很抱歉是以issue的形式来发这种问题,实在是没能找到你的联系方式...

把你的Python代码翻译成Go后,转换出的图片:
![output-1](https://github.com/Fire-Paw-DST-Manager/DST-Common/assets/48203714/0aa84a85-55cb-4dc9-8a7a-05e03cbeae6b)

把如下3行去掉后,转换的结果:
```go
func decode565(color uint16) (uint8, uint8, uint8) {
	r := (color >> 11) & 0b0001_1111 // 0b11111000_00000000
	g := (color >> 5) & 0b0011_1111  // 0b00000111_11100000
	b := (color >> 0) & 0b0001_1111  // 0b00000000_00011111
	// r = (r << 3) | (r >> 2)
	// g = (g << 2) | (g >> 4)
	// b = (b << 3) | (b >> 2)
	return uint8(r), uint8(g), uint8(b)
}
```
![output-2](https://github.com/Fire-Paw-DST-Manager/DST-Common/assets/48203714/ec3a08a8-7ed4-48f3-ab02-c0f28548f141)

你的另一个仓库里面所使用的图片:  
`DstServerHelper`/create-cluster-demo/misc/worldsettings_customization.webp
![worldsettings_customization](https://github.com/Fire-Paw-DST-Manager/DST-Common/assets/48203714/00c065c2-d07c-4e31-9491-e32398e19f9d)

**Comment by yechentide** [comment]
这是最接近的了, 但还是有点暗

![output](https://github.com/Fire-Paw-DST-Manager/DST-Common/assets/48203714/0c11daad-539f-4722-8414-1a2b3e7c7e98)

<img width="651" alt="SCR-20240324-rdff" src="https://github.com/Fire-Paw-DST-Manager/DST-Common/assets/48203714/9c1776e5-b5a9-435e-bd82-ab2947119cb9">

**Comment by sukeme** [comment]
不知道为什么没有邮件通知，刚看到。

情况一：我没有遇到过，不太清楚；
情况二：这三行是用来将低位数的数据补全成八位的，对于 r 来说，等同于 r = round(r / 31 * 255)。所以删掉后会导致偏色，由于八位里只用了五或六位，所以会偏暗，同时绿色占六位其它只有五位所以会偏绿;
情况三：添加的算法一定程度上修正了偏色，但是这个算法很奇怪，比如 r 从五位转换到八位时，按五位、八位、这个算法的顺序：(1, 8, 16), (31, 255, 196)，可以看出偏色很多，暗的地方不够暗，亮的地方不够亮。同时，由于是在所有计算之后进行的修正，所以在之前的一些运算过程中，由于位数的不同也可能产生些许误差。

在所有计算完成后再修正颜色，可以看到是没有混乱条纹的，只有偏色问题（这里也有可能是），而 decode565 本身应该是没有问题的，问题应该是出现在这两步中间（也有可能是因为添加的算法的计算结果最大只有 199，所以后续计算没出问题，但是既然情况一中白色与黑色区域没有问题，我认为可能性较小），所以我猜测可能是修正成 888 格式数据之后，在这两步中间某个地方的运算结果溢出八位，导致颜色信息出问题，你可以用很小比如 4*4 像素的数据测试，打印计算过程中的结果看是哪里出的问题。

**Comment by yechentide** [comment]
被issue关闭的邮件给提醒了一下还有这个hhh

秋天为止工作都太忙了,开源的那个软件我暂时弃坑了.
你说的我都还没试, 明年有空试试看.
多谢你的建议!
